//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarRentalDbV2Entities : DbContext
    {
        public CarRentalDbV2Entities()
            : base("name=CarRentalDbV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BranchesTable> BranchesTables { get; set; }
        public virtual DbSet<CarsTable> CarsTables { get; set; }
        public virtual DbSet<CarsTypesTable> CarsTypesTables { get; set; }
        public virtual DbSet<RentTable> RentTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UsersTable> UsersTables { get; set; }
    }
}
