//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarsTable()
        {
            this.RentTables = new HashSet<RentTable>();
        }
    
        public int ID { get; set; }
        public int CarType { get; set; }
        public int CarKilometer { get; set; }
        public string CarImg { get; set; }
        public bool CarStatus { get; set; }
        public string CarlicenseNumber { get; set; }
        public int CarLocation { get; set; }
    
        public virtual BranchesTable BranchesTable { get; set; }
        public virtual CarsTypesTable CarsTypesTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentTable> RentTables { get; set; }
    }
}
